// data/model/Note.java
package com.example.notetaker.data.model;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * This class represents a Note entity that is stored in the Room database.
 * Each note has an auto-generated unique ID, a title, and content.
 * @author Jubaer
 * @version 1.0
 */
@Entity(tableName = "note_table")
public class Note {

    /**
     * The primary key for the note, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;
    private String title;
    private String content;

    /**
     * Constructs a new Note with a given title and content.
     *
     * @param title   The title of the note.
     * @param content The content of the note.
     */
    public Note(String title, String content) {
        this.title = title;
        this.content = content;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getContent() {
        return content;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setContent(String content) {
        this.content = content;
    }
}
